name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          version: v2.4

      - name: Lint
        run: deno lint

      - name: Format
        run: deno fmt --check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          version: v2.4

      - name: Test
        run: deno test
